### ISSUE TITLE
关于第一次作业公式推理部分的答案

### ISSUE THREAD

**Issue by SinnohHo-Oh** [liblaf/deep-learning-coursework#3]
### 🥰 Feature Description

同学你好！
我是一名来自求真书院的学生，现在在读博二。
我看到你写的第一次作业，我觉得它写的很不错！不过我并没有这次作业的标准答案，请问一下你有第一次作业的标准答案吗？我很想参考一下！
谢谢你！

### 🧐 Proposed Solution

。

**Comment by liblaf** [comment]
@SinnohHo-Oh 感谢您的问题! 不过很抱歉, 我也没有这次作业的标准答案.
